"""L0 Transport — messaging, task queues, worker registries, data transport.

Re-exports from canonical source modules. Use ``from nsgablack.core.resources.transport import TaskQueueBackend`` etc.
"""

from nsgablack.core.resources.backends import (  # type: ignore[attr-defined]
    TaskQueueBackend,
    TaskResultBackend,
    TaskStateBackend,
    WorkerRegistryBackend,
    DataTransportBackend,
    ArtifactDataTransportBackend,
    InlineDataTransportBackend,
    InMemoryTaskQueueBackend,
    InMemoryTaskResultBackend,
    InMemoryTaskStateBackend,
    InMemoryWorkerRegistryBackend,
    L0RuntimeBackend,
    InMemoryL0RuntimeBackend,
    RedisL0RuntimeBackend,
    RedisTaskQueueBackend,
    RedisTaskResultBackend,
    RedisTaskStateBackend,
    RedisWorkerRegistryBackend,
    TASK_ENVELOPE_SCHEMA,
    TASK_RESULT_SCHEMA,
    infer_result_run_id,
    infer_task_run_id,
    result_from_json,
    result_to_json,
    task_from_json,
    task_to_json,
)
from nsgablack.core.resources.backends_s3 import S3ArtifactBackend
from nsgablack.core.resources.backends_postgres import (
    PostgresL0RuntimeBackend,
    PostgresTaskQueueBackend,
    PostgresTaskResultBackend,
    PostgresTaskStateBackend,
    PostgresWorkerRegistryBackend,
)
from nsgablack.core.solver_manager import (  # type: ignore[attr-defined]
    InMemoryMessageQueue,
    SQLiteMessageQueue,
    ResourceEvent,
)

__all__ = [
    "TaskQueueBackend",
    "TaskResultBackend",
    "TaskStateBackend",
    "WorkerRegistryBackend",
    "DataTransportBackend",
    "ArtifactDataTransportBackend",
    "InlineDataTransportBackend",
    "InMemoryTaskQueueBackend",
    "InMemoryTaskResultBackend",
    "InMemoryTaskStateBackend",
    "InMemoryWorkerRegistryBackend",
    "L0RuntimeBackend",
    "InMemoryL0RuntimeBackend",
    "RedisL0RuntimeBackend",
    "RedisTaskQueueBackend",
    "RedisTaskResultBackend",
    "RedisTaskStateBackend",
    "RedisWorkerRegistryBackend",
    "PostgresL0RuntimeBackend",
    "PostgresTaskQueueBackend",
    "PostgresTaskResultBackend",
    "PostgresTaskStateBackend",
    "PostgresWorkerRegistryBackend",
    "S3ArtifactBackend",
    "TASK_ENVELOPE_SCHEMA",
    "TASK_RESULT_SCHEMA",
    "infer_result_run_id",
    "infer_task_run_id",
    "result_from_json",
    "result_to_json",
    "task_from_json",
    "task_to_json",
    "InMemoryMessageQueue",
    "SQLiteMessageQueue",
    "ResourceEvent",
]
