"""L0 resource, task and worker orchestration surface.

This package is the stable import surface for nsgablack L0 concepts. The
legacy lease primitives still live in ``core.solver_manager`` for backward
compatibility; this module re-exports them and adds the missing task/worker
protocol objects.
"""

from __future__ import annotations

from .backends import (
    ArtifactBackend,
    ArtifactDataTransportBackend,
    DataTransportBackend,
    FilesystemArtifactBackend,
    InMemoryArtifactBackend,
    InMemoryL0RuntimeBackend,
    InMemoryTaskQueueBackend,
    InMemoryTaskResultBackend,
    InMemoryTaskStateBackend,
    InMemoryWorkerRegistryBackend,
    InlineDataTransportBackend,
    L0RuntimeBackend,
    RedisL0RuntimeBackend,
    RedisTaskQueueBackend,
    RedisTaskResultBackend,
    RedisTaskStateBackend,
    RedisWorkerRegistryBackend,
    TASK_ENVELOPE_SCHEMA,
    TASK_RESULT_SCHEMA,
    TaskQueueBackend,
    TaskResultBackend,
    TaskStateBackend,
    WorkerRegistryBackend,
    infer_result_run_id,
    infer_task_run_id,
    result_from_json,
    result_to_json,
    task_from_json,
    task_to_json,
)
from .backends_s3 import S3ArtifactBackend
from .backends_postgres import (
    PostgresL0RuntimeBackend,
    PostgresTaskQueueBackend,
    PostgresTaskResultBackend,
    PostgresTaskStateBackend,
    PostgresWorkerRegistryBackend,
)
from .model import (
    DataRef,
    InMemoryResourceScheduler,
    InMemoryWorkerRegistry,
    ResourceRequirement,
    ScheduledTask,
    TaskEnvelope,
    TaskResult,
    WorkerDescriptor,
)
from .compute.pool import PoolScheduler, PoolTask, PoolResult
from .probe import (
    build_local_worker_descriptor,
    detect_cuda_devices,
    detect_local_resource_offer,
    detect_total_memory_mb,
)
from .storage.lease import (
    InMemoryLeaseStore,
    InMemoryMessageQueue,
    ResourceAllocator,
    ResourceBudgetError,
    ResourceEvent,
    ResourceLease,
    ResourceOffer,
    ResourcePolicy,
    ResourceRequest,
    SQLiteLeaseStore,
    SQLiteMessageQueue,
)

__all__ = [
    "ArtifactBackend",
    "ArtifactDataTransportBackend",
    "S3ArtifactBackend",
    "DataTransportBackend",
    "DataRef",
    "FilesystemArtifactBackend",
    "InMemoryArtifactBackend",
    "InMemoryL0RuntimeBackend",
    "InMemoryResourceScheduler",
    "InMemoryTaskQueueBackend",
    "InMemoryTaskResultBackend",
    "InMemoryTaskStateBackend",
    "InMemoryWorkerRegistryBackend",
    "InMemoryWorkerRegistry",
    "InlineDataTransportBackend",
    "L0RuntimeBackend",
    "PoolScheduler",
    "PoolTask",
    "PoolResult",
    "PostgresL0RuntimeBackend",
    "PostgresTaskQueueBackend",
    "PostgresTaskResultBackend",
    "PostgresTaskStateBackend",
    "PostgresWorkerRegistryBackend",
    "RedisL0RuntimeBackend",
    "RedisTaskQueueBackend",
    "RedisTaskResultBackend",
    "RedisTaskStateBackend",
    "RedisWorkerRegistryBackend",
    "ResourceRequirement",
    "ScheduledTask",
    "TASK_ENVELOPE_SCHEMA",
    "TASK_RESULT_SCHEMA",
    "TaskEnvelope",
    "TaskQueueBackend",
    "TaskResult",
    "TaskResultBackend",
    "TaskStateBackend",
    "WorkerDescriptor",
    "WorkerRegistryBackend",
    "build_local_worker_descriptor",
    "detect_cuda_devices",
    "detect_local_resource_offer",
    "detect_total_memory_mb",
    "infer_result_run_id",
    "infer_task_run_id",
    "result_from_json",
    "result_to_json",
    "task_from_json",
    "task_to_json",
    "ResourceAllocator",
    "ResourceBudgetError",
    "ResourceEvent",
    "ResourceLease",
    "ResourceOffer",
    "ResourcePolicy",
    "ResourceRequest",
    "InMemoryLeaseStore",
    "InMemoryMessageQueue",
    "SQLiteLeaseStore",
    "SQLiteMessageQueue",
]
