"""Core modules exposed by NSGABlack."""

from __future__ import annotations

from .acceleration import (
    AccelerationError,
    AccelerationFacade,
    AccelerationRegistry,
    AsyncHandle,
    ExecutionResult,
    GpuBackend,
    ProcessPoolBackend,
    ThreadPoolBackend,
)
from .acceleration_helpers import maybe_accel_map, maybe_accel_run
from .base import BlackBoxProblem
from .blank_solver import SolverBase
from .composable_solver import ComposableSolver
from .config import StorageConfig, _apply_storage_config
from .control_plane import (
    BaseController,
    BudgetController,
    ControlArbiter,
    ControlDecision,
    EvaluationBudgetExceeded,
    RuntimeController,
    StopController,
)
from .evolution_solver import EvolutionSolver
from .evaluation_runtime import (
    EvaluationMediator,
    EvaluationMediatorConfig,
    EvaluationProvider,
    EvaluationProviderContractError,
)
from .nested_solver import (
    InnerRuntimeConfig,
    InnerRuntimeEvaluator,
    InnerSolveRequest,
    InnerSolveResult,
    TaskInnerRuntimeEvaluator,
)
from .solver_stage import (
    ArtifactRef,
    CompletionPolicy,
    SerialStageSolver,
    StageRunner,
    StageSpec,
)
from .solver_manager import (
    InMemoryLeaseStore,
    InMemoryMessageQueue,
    PhaseSpec,
    RegimeSpec,
    ResourceAllocator,
    ResourceBudgetError,
    ResourceEvent,
    ResourceLease,
    ResourceOffer,
    ResourcePolicy,
    ResourceRequest,
    SQLiteLeaseStore,
    SQLiteMessageQueue,
    SolverManager,
)
from .solver_result import DEFAULT_CASE_RESULT_INLINE_MAX_BYTES, build_solver_result
from blackbase.types import SolveQuality, SolverResult
from .resources import (
    ArtifactBackend,
    DataTransportBackend,
    DataRef,
    FilesystemArtifactBackend,
    InMemoryL0RuntimeBackend,
    InMemoryResourceScheduler,
    InMemoryWorkerRegistry,
    L0RuntimeBackend,
    RedisL0RuntimeBackend,
    ResourceRequirement,
    ScheduledTask,
    TaskEnvelope,
    TaskQueueBackend,
    TaskResult,
    TaskResultBackend,
    TaskStateBackend,
    WorkerDescriptor,
    WorkerRegistryBackend,
    build_local_worker_descriptor,
    detect_local_resource_offer,
)
from ..adapters import AlgorithmAdapter, CompositeAdapter, RoleAdapter, RoleRouterAdapter
from .interfaces import (
    BiasInterface,
    PluginInterface,
    OptimizationContext,
    RepresentationInterface,
    VisualizationInterface,
    create_bias_context,
    has_bias_module,
    has_numba,
    has_representation_module,
    has_visualization_module,
    load_bias_module,
    load_representation_pipeline,
)

__all__ = [
    "BlackBoxProblem",
    "EvolutionSolver",
    "SolverBase",
    "AccelerationRegistry",
    "AccelerationFacade",
    "ExecutionResult",
    "AccelerationError",
    "AsyncHandle",
    "ThreadPoolBackend",
    "ProcessPoolBackend",
    "GpuBackend",
    "maybe_accel_run",
    "maybe_accel_map",
    "StorageConfig",
    "AlgorithmAdapter",
    "CompositeAdapter",
    "ComposableSolver",
    "RoleAdapter",
    "RoleRouterAdapter",
    "BiasInterface",
    "RepresentationInterface",
    "VisualizationInterface",
    "PluginInterface",
    "BaseController",
    "BudgetController",
    "ControlDecision",
    "ControlArbiter",
    "EvaluationBudgetExceeded",
    "RuntimeController",
    "StopController",
    "EvaluationMediator",
    "EvaluationMediatorConfig",
    "EvaluationProvider",
    "EvaluationProviderContractError",
    "InnerSolveRequest",
    "InnerSolveResult",
    "InnerRuntimeEvaluator",
    "TaskInnerRuntimeEvaluator",
    "InnerRuntimeConfig",
    "SolverManager",
    "StageSpec",
    "StageRunner",
    "SerialStageSolver",
    "CompletionPolicy",
    "ArtifactRef",
    "InMemoryLeaseStore",
    "InMemoryMessageQueue",
    "ResourceAllocator",
    "ResourceLease",
    "ResourceOffer",
    "ResourcePolicy",
    "ResourceRequest",
    "ResourceEvent",
    "SQLiteLeaseStore",
    "SQLiteMessageQueue",
    "RegimeSpec",
    "PhaseSpec",
    "ResourceBudgetError",
    "ArtifactBackend",
    "DataTransportBackend",
    "DataRef",
    "FilesystemArtifactBackend",
    "InMemoryL0RuntimeBackend",
    "ResourceRequirement",
    "L0RuntimeBackend",
    "RedisL0RuntimeBackend",
    "WorkerDescriptor",
    "TaskEnvelope",
    "TaskQueueBackend",
    "TaskResult",
    "TaskResultBackend",
    "TaskStateBackend",
    "ScheduledTask",
    "InMemoryWorkerRegistry",
    "InMemoryResourceScheduler",
    "WorkerRegistryBackend",
    "build_local_worker_descriptor",
    "detect_local_resource_offer",
    "SolverResult",
    "SolveQuality",
    "DEFAULT_CASE_RESULT_INLINE_MAX_BYTES",
    "build_solver_result",
    "OptimizationContext",
    "has_bias_module",
    "has_representation_module",
    "has_visualization_module",
    "has_numba",
    "load_bias_module",
    "load_representation_pipeline",
    "create_bias_context",
]
