from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
from typing import Any, Callable, Dict, Mapping, Optional

import numpy as np

from .backend_contract import BackendSolveRequest


NetlistBuilder = Callable[[BackendSolveRequest], str]
ResultParser = Callable[[BackendSolveRequest, Path], Mapping[str, Any]]


@dataclass
class NgspiceBackendConfig:
    command: str = "ngspice"
    timeout_ms: int = 30000
    work_dir: Optional[str] = None
    mock_when_unavailable: bool = True
    mock_objective_scale: float = 1.0
    mock_violation: float = 0.0


class NgspiceBackend:
    """Minimal ngspice backend implementing BackendSolver.solve(request).

    Notes:
    - Intended for InnerSolverPlugin backend path.
    - If ngspice is unavailable and mock_when_unavailable=True, returns a deterministic mock result.
    - For real projects, provide custom netlist_builder/result_parser.
    """

    def __init__(
        self,
        *,
        config: Optional[NgspiceBackendConfig] = None,
        netlist_builder: Optional[NetlistBuilder] = None,
        result_parser: Optional[ResultParser] = None,
    ) -> None:
        self.cfg = config or NgspiceBackendConfig()
        self.netlist_builder = netlist_builder
        self.result_parser = result_parser

    def _default_netlist(self, request: BackendSolveRequest) -> str:
        cand = np.asarray(request.candidate, dtype=float).reshape(-1)
        r1 = float(abs(cand[0])) if cand.size > 0 else 1.0
        r1 = max(1e-3, r1)
        return (
            "* Minimal ngspice template generated by NgspiceBackend\n"
            "V1 in 0 DC 1.0\n"
            f"R1 in out {r1}\n"
            "R2 out 0 1.0\n"
            ".op\n"
            ".print dc v(out)\n"
            ".end\n"
        )

    def _parse_measure_lines(self, log_text: str) -> Dict[str, float]:
        out: Dict[str, float] = {}
        for line in log_text.splitlines():
            m = re.match(r"^\s*([A-Za-z_]\w*)\s*=\s*([-+0-9.eE]+)\s*$", line.strip())
            if not m:
                continue
            try:
                out[m.group(1)] = float(m.group(2))
            except Exception:
                continue
        return out

    def _build_mock(self, request: BackendSolveRequest, status: str) -> Dict[str, Any]:
        cand = np.asarray(request.candidate, dtype=float).reshape(-1)
        objective = float(np.sum(cand * cand) * float(self.cfg.mock_objective_scale))
        return {
            "status": status,
            "objective": objective,
            "violation": float(self.cfg.mock_violation),
            "metrics": {
                "ngspice.mode": "mock",
                "ngspice.command": self.cfg.command,
            },
        }

    def solve(self, request: BackendSolveRequest) -> Mapping[str, Any]:
        if shutil.which(self.cfg.command) is None:
            if self.cfg.mock_when_unavailable:
                return self._build_mock(request, status="mock_unavailable")
            raise RuntimeError(f"ngspice command not found: {self.cfg.command}")

        with tempfile.TemporaryDirectory(dir=self.cfg.work_dir) as tmpdir:
            tmp = Path(tmpdir)
            netlist_path = tmp / "case.cir"
            log_path = tmp / "ngspice.log"
            netlist_text = self.netlist_builder(request) if callable(self.netlist_builder) else self._default_netlist(request)
            netlist_path.write_text(netlist_text, encoding="utf-8")

            cmd = [self.cfg.command, "-b", "-o", str(log_path), str(netlist_path)]
            timeout_s = max(0.001, float(self.cfg.timeout_ms) / 1000.0)
            try:
                proc = subprocess.run(
                    cmd,
                    cwd=str(tmp),
                    capture_output=True,
                    text=True,
                    timeout=timeout_s,
                    check=False,
                )
            except subprocess.TimeoutExpired as exc:
                raise TimeoutError(f"ngspice timeout after {self.cfg.timeout_ms} ms") from exc

            if proc.returncode != 0:
                stderr = (proc.stderr or "").strip()
                raise RuntimeError(f"ngspice failed returncode={proc.returncode}: {stderr[:300]}")

            if callable(self.result_parser):
                parsed = dict(self.result_parser(request, log_path))
            else:
                log_text = log_path.read_text(encoding="utf-8", errors="replace") if log_path.exists() else ""
                measures = self._parse_measure_lines(log_text)
                if "objective" in measures:
                    objective = float(measures["objective"])
                else:
                    cand = np.asarray(request.candidate, dtype=float).reshape(-1)
                    objective = float(np.sum(cand * cand))
                parsed = {
                    "status": "ok",
                    "objective": objective,
                    "violation": 0.0,
                    "metrics": {
                        "ngspice.mode": "real",
                        "ngspice.returncode": int(proc.returncode),
                        "ngspice.command": " ".join(cmd),
                        "ngspice.log_path": str(log_path),
                        "ngspice.measures": measures,
                    },
                }
            return parsed

