# -*- coding: utf-8 -*-
"""Local Catalog entries for production_scheduling case."""

from __future__ import annotations

from nsgablack.catalog import CatalogEntry


def get_project_entries():
    return [
        CatalogEntry(
            key="solver.production_schedule",
            title="Production Scheduling Solver Entry",
            kind="example",
            import_path="build_solver:build_solver",
            tags=("project", "production", "scheduling", "example"),
            summary="Case entrypoint for production scheduling assembly.",
            companions=("project.problem.production_schedule", "project.pipeline.production_schedule"),
            context_requires=(),
            context_provides=(),
            context_mutates=(),
            context_cache=(),
            context_notes=("Assembly-only entrypoint; context contracts are delegated to wired components.",),
            use_when=("Run this case in Run Inspector/doctor/project catalog.",),
            minimal_wiring=("python build_solver.py",),
            required_companions=("project.problem.production_schedule", "project.pipeline.production_schedule"),
            config_keys=("solver", "parallel", "workers", "generations", "pop_size"),
            example_entry="build_solver:build_solver",
        ),
        CatalogEntry(
            key="problem.production_schedule",
            title="ProductionSchedulingProblem",
            kind="tool",
            import_path="refactor_problem:ProductionSchedulingProblem",
            tags=("project", "problem", "production", "scheduling"),
            summary="Production scheduling problem semantics and objective definition.",
            companions=("project.pipeline.production_schedule",),
            context_requires=(),
            context_provides=(),
            context_mutates=(),
            context_cache=(),
            context_notes=("Problem layer does not mutate runtime context directly.",),
            use_when=("Define objective/constraint semantics for this production case.",),
            minimal_wiring=(
                "from refactor_problem import ProductionSchedulingProblem",
                "problem = ProductionSchedulingProblem(...)",
            ),
            required_companions=("project.pipeline.production_schedule",),
            config_keys=("machines", "materials", "days"),
            example_entry="build_solver:build_solver",
        ),
        CatalogEntry(
            key="pipeline.production_schedule",
            title="build_schedule_pipeline",
            kind="representation",
            import_path="refactor_pipeline:build_schedule_pipeline",
            tags=("project", "pipeline", "repair", "production"),
            summary="Schedule representation pipeline (initializer/mutator/repair).",
            companions=("project.problem.production_schedule",),
            context_requires=(),
            context_provides=(),
            context_mutates=(),
            context_cache=(),
            context_notes=("Primary responsibility is schedule feasibility shaping.",),
            use_when=("Need production schedule init/mutate/repair wiring.",),
            minimal_wiring=("pipeline = build_schedule_pipeline(...)",),
            required_companions=("project.problem.production_schedule",),
            config_keys=("shift_limit", "use_supply_aware_repair"),
            example_entry="build_solver:build_solver",
        ),
        CatalogEntry(
            key="bias.production_schedule",
            title="build_production_bias_module",
            kind="bias",
            import_path="refactor_bias:build_production_bias_module",
            tags=("project", "bias", "domain", "production"),
            summary="Domain preference bundle for production scheduling.",
            companions=("project.problem.production_schedule",),
            context_requires=(),
            context_provides=(),
            context_mutates=(),
            context_cache=(),
            context_notes=("Bias layer expresses soft preferences and does not enforce hard feasibility.",),
            use_when=("Need domain-level preference shaping for production objectives.",),
            minimal_wiring=(
                "from refactor_bias import build_production_bias_module",
                "bias_module = build_production_bias_module(problem, weights=...)",
            ),
            required_companions=("project.problem.production_schedule",),
            config_keys=("weights",),
            example_entry="build_solver:build_solver",
        ),
        CatalogEntry(
            key="tool.production_data_loader",
            title="load_production_data",
            kind="tool",
            import_path="refactor_data:load_production_data",
            tags=("project", "data", "loader", "production"),
            summary="Data loader for BOM and supply matrices in this case.",
            companions=(),
            context_requires=(),
            context_provides=(),
            context_mutates=(),
            context_cache=(),
            context_notes=("Data loader returns structured case input and does not mutate context.",),
            use_when=("Load BOM/supply and normalize to case input arrays.",),
            minimal_wiring=("data = load_production_data(...)",),
            required_companions=(),
            config_keys=("bom_path", "supply_path", "machines", "materials", "days"),
            example_entry="build_solver:build_solver",
        ),
    ]

